In [13]:
#Thanksgiving data
import numpy as np
import pandas as pd
data = pd.read_csv("thanks.csv", encoding="Latin-1")
data.head()

,RespondentID,Do you celebrate Thanksgiving?,What is typically the main dish at your Thanksgiving dinner?,What is typically the main dish at your Thanksgiving dinner? - Other (please specify),How is the main dish typically cooked?,How is the main dish typically cooked? - Other (please specify),What kind of stuffing/dressing do you typically have?,What kind of stuffing/dressing do you typically have? - Other (please specify),What type of cranberry saucedo you typically have?,What type of cranberry saucedo you typically have? - Other (please specify),...,Have you ever tried to meet up with hometown friends on Thanksgiving night?,"Have you ever attended a ""Friendsgiving?""",Will you shop any Black Friday sales on Thanksgiving Day?,Do you work in retail?,Will you employer make you work on Black Friday?,How would you describe where you live?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region
0,4337954960,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,None,NaN,...,Yes,No,No,No,NaN,Suburban,18 - 29,Male,"$75,000 to $99,999",Middle Atlantic
1,4337951949,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Other (please specify),Homemade cranberry gelatin ring,...,No,No,Yes,No,NaN,Rural,18 - 29,Female,"$50,000 to $74,999",East South Central
2,4337935621,Yes,Turkey,NaN,Roasted,NaN,Rice-based,NaN,Homemade,NaN,...,Yes,Yes,Yes,No,NaN,Suburban,18 - 29,Male,"$0 to $9,999",Mountain
3,4337933040,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$200,000 and up",Pacific
4,4337931983,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$100,000 to $124,999",Pacific

In [14]:
data.columns[:]
data.columns[3:4]

Index(['What is typically the main dish at your Thanksgiving dinner? - Other (please specify)'], dtype='object')

In [15]:
data.tail(5)

,RespondentID,Do you celebrate Thanksgiving?,What is typically the main dish at your Thanksgiving dinner?,What is typically the main dish at your Thanksgiving dinner? - Other (please specify),How is the main dish typically cooked?,How is the main dish typically cooked? - Other (please specify),What kind of stuffing/dressing do you typically have?,What kind of stuffing/dressing do you typically have? - Other (please specify),What type of cranberry saucedo you typically have?,What type of cranberry saucedo you typically have? - Other (please specify),...,Have you ever tried to meet up with hometown friends on Thanksgiving night?,"Have you ever attended a ""Friendsgiving?""",Will you shop any Black Friday sales on Thanksgiving Day?,Do you work in retail?,Will you employer make you work on Black Friday?,How would you describe where you live?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region
1053,4335944082,Yes,Turkey,NaN,Roasted,NaN,Bread-based,NaN,Homemade,NaN,...,Yes,Yes,No,No,NaN,Rural,30 - 44,Female,"$100,000 to $124,999",Mountain
1054,4335943173,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,No,No,No,No,NaN,Suburban,60+,Female,"$50,000 to $74,999",Pacific
1055,4335943060,Yes,Other (please specify),Duck,Baked,NaN,Rice-based,NaN,None,NaN,...,Yes,Yes,Yes,No,NaN,Urban,60+,Male,"$100,000 to $124,999",Pacific
1056,4335934708,Yes,Turkey,NaN,Baked,NaN,None,NaN,Homemade,NaN,...,Yes,No,Yes,Yes,Yes,NaN,NaN,NaN,NaN,NaN
1057,4335894916,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,Yes,Yes,Yes,No,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
#Unique Method
#a=data["Do you celebrate Thanksgiving?"]
print(a)
a=data["Do you celebrate Thanksgiving?"].unique()
b=np.array(data["Do you celebrate Thanksgiving?"].unique())
b

NameError: name 'a' is not defined

In [ ]:
a=data.columns[50:]
a

In [ ]:
#Series Function
data["What is your gender?"].value_counts(dropna=False)

In [ ]:
#To get the gender column's data in 0 and 1 form
import math

def gender_code(gender_string):
    if isinstance(gender_string, float) and math.isnan(gender_string):
        return gender_string
    return int(gender_string == "Female")

data["gender"] = data["What is your gender?"].apply(gender_code)
data["gender"].value_counts(dropna=False)

In [19]:
#Apply method on pandas datafram which works across each column in the dataframe
data.apply(lambda x: x.dtype).head()

RespondentID                                                                             object
Do you celebrate Thanksgiving?                                                           object
What is typically the main dish at your Thanksgiving dinner?                             object
What is typically the main dish at your Thanksgiving dinner? - Other (please specify)    object
How is the main dish typically cooked?                                                   object
dtype: object

In [20]:
#Series Function
data["How much total combined money did all members of your HOUSEHOLD earn last year?"].value_counts(dropna=False)

$25,000 to $49,999      180
Prefer not to answer    136
$50,000 to $74,999      135
$75,000 to $99,999      133
$100,000 to $124,999    111
$200,000 and up          80
$10,000 to $24,999       68
$0 to $9,999             66
$125,000 to $149,999     49
$150,000 to $174,999     40
NaN                      33
$175,000 to $199,999     27
Name: How much total combined money did all members of your HOUSEHOLD earn last year?, dtype: int64

In [21]:
#Cleaning the Income Column to get values in Numericalform
#checks for float and math.isnan checks whether the argument is a number and equates to NAN
#checks if the float x is a nan
#pandas cannot store NaN values in integer columns so any value comes nan, the whole col is chanaged to float
import numpy as np

def clean_income(value):
    if value == "$200,000 and up":
        return 200000
    elif value == "Prefer not to answer":
        return np.nan
    elif isinstance(value, float) and math.isnan(value):
        return np.nan
    value = value.replace(",", "").replace("$", "")
    income_high, income_low = value.split(" to ")
    return (int(income_high) + int(income_low)) / 2

data["income"] = data["How much total combined money did all members of your HOUSEHOLD earn last year?"].apply(clean_income)
#data["income"]
data["income"]

data.head(5)

,RespondentID,Do you celebrate Thanksgiving?,What is typically the main dish at your Thanksgiving dinner?,What is typically the main dish at your Thanksgiving dinner? - Other (please specify),How is the main dish typically cooked?,How is the main dish typically cooked? - Other (please specify),What kind of stuffing/dressing do you typically have?,What kind of stuffing/dressing do you typically have? - Other (please specify),What type of cranberry saucedo you typically have?,What type of cranberry saucedo you typically have? - Other (please specify),...,"Have you ever attended a ""Friendsgiving?""",Will you shop any Black Friday sales on Thanksgiving Day?,Do you work in retail?,Will you employer make you work on Black Friday?,How would you describe where you live?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region,income
0,4337954960,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,None,NaN,...,No,No,No,NaN,Suburban,18 - 29,Male,"$75,000 to $99,999",Middle Atlantic,87499.5
1,4337951949,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Other (please specify),Homemade cranberry gelatin ring,...,No,Yes,No,NaN,Rural,18 - 29,Female,"$50,000 to $74,999",East South Central,62499.5
2,4337935621,Yes,Turkey,NaN,Roasted,NaN,Rice-based,NaN,Homemade,NaN,...,Yes,Yes,No,NaN,Suburban,18 - 29,Male,"$0 to $9,999",Mountain,4999.5
3,4337933040,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,No,No,No,NaN,Urban,30 - 44,Male,"$200,000 and up",Pacific,200000.0
4,4337931983,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,No,No,No,NaN,Urban,30 - 44,Male,"$100,000 to $124,999",Pacific,112499.5

In [22]:
print(data["income"])
#Series Function

data["What type of cranberry saucedo you typically have?"].value_counts()
#data["What type of cranberry saucedo you typically have?"]

0        87499.5
1        62499.5
2         4999.5
3       200000.0
4       112499.5
5         4999.5
6        37499.5
7            NaN
8        87499.5
9        37499.5
10       37499.5
11       37499.5
12        4999.5
13        4999.5
14       62499.5
15      200000.0
16      200000.0
17       87499.5
18       37499.5
19       87499.5
20       87499.5
21        4999.5
22        4999.5
23        4999.5
24       62499.5
25      200000.0
26       62499.5
27      112499.5
28           NaN
29       87499.5
          ...
1028         NaN
1029     62499.5
1030     17499.5
1031     87499.5
1032         NaN
1033     87499.5
1034         NaN
1035     37499.5
1036     62499.5
1037     17499.5
1038    112499.5
1039     87499.5
1040     62499.5
1041     37499.5
1042    137499.5
1043     87499.5
1044     37499.5
1045     87499.5
1046     17499.5
1047     37499.5
1048     87499.5
1049         NaN
1050    137499.5
1051    137499.5
1052      4999.5
1053    112499.5
1054     62499.5
1055    112499.5
1056         NaN
1057         NaN
Name: income, Length: 1058, dtype: float64

Canned                    502
Homemade                  301
None                      146
Other (please specify)     25
Name: What type of cranberry saucedo you typically have?, dtype: int64

In [23]:
#Grouping Data
homemade = data[data["What type of cranberry saucedo you typically have?"] == "Homemade"]
canned = data[data["What type of cranberry saucedo you typically have?"] == "Canned"]
print(homemade["income"].mean())
print(canned["income"].mean())
print(homemade["What type of cranberry saucedo you typically have?"])
print(canned["What type of cranberry saucedo you typically have?"])

94878.1072874494
83823.40340909091
2       Homemade
3       Homemade
5       Homemade
7       Homemade
13      Homemade
14      Homemade
16      Homemade
20      Homemade
21      Homemade
23      Homemade
25      Homemade
28      Homemade
30      Homemade
32      Homemade
33      Homemade
37      Homemade
39      Homemade
42      Homemade
44      Homemade
46      Homemade
52      Homemade
54      Homemade
56      Homemade
57      Homemade
62      Homemade
64      Homemade
66      Homemade
70      Homemade
82      Homemade
83      Homemade
          ...
921     Homemade
929     Homemade
931     Homemade
933     Homemade
940     Homemade
943     Homemade
944     Homemade
950     Homemade
953     Homemade
959     Homemade
960     Homemade
975     Homemade
983     Homemade
984     Homemade
993     Homemade
996     Homemade
1008    Homemade
1011    Homemade
1012    Homemade
1014    Homemade
1016    Homemade
1017    Homemade
1025    Homemade
1027    Homemade
1030    Homemade
1034    Homemade
1048    Homemade
1049    Homemade
1053    Homemade
1056    Homemade
Name: What type of cranberry saucedo you typically have?, Length: 301, dtype: object
4       Canned
6       Canned
8       Canned
11      Canned
12      Canned
15      Canned
18      Canned
19      Canned
26      Canned
27      Canned
38      Canned
43      Canned
48      Canned
53      Canned
58      Canned
59      Canned
60      Canned
68      Canned
69      Canned
71      Canned
74      Canned
76      Canned
79      Canned
80      Canned
86      Canned
87      Canned
89      Canned
90      Canned
91      Canned
97      Canned
         ...
995     Canned
998     Canned
999     Canned
1002    Canned
1003    Canned
1004    Canned
1005    Canned
1010    Canned
1013    Canned
1019    Canned
1021    Canned
1022    Canned
1023    Canned
1024    Canned
1026    Canned
1029    Canned
1033    Canned
1035    Canned
1038    Canned
1039    Canned
1040    Canned
1041    Canned
1042    Canned
1044    Canned
1045    Canned
1046    Canned
1047    Canned
1051    Canned
1054    Canned
1057    Canned
Name: What type of cranberry saucedo you typically have?, Length: 502, dtype: object

In [25]:
#Grouping Data
grouped = data.groupby("What type of cranberry saucedo you typically have?")
grouped

In [26]:
grouped.groups

{'Canned': Int64Index([   4,    6,    8,   11,   12,   15,   18,   19,   26,   27,
             ...
             1040, 1041, 1042, 1044, 1045, 1046, 1047, 1051, 1054, 1057],
            dtype='int64', length=502),
 'Homemade': Int64Index([   2,    3,    5,    7,   13,   14,   16,   20,   21,   23,
             ...
             1016, 1017, 1025, 1027, 1030, 1034, 1048, 1049, 1053, 1056],
            dtype='int64', length=301),
 'None': Int64Index([   0,   17,   24,   29,   34,   36,   40,   47,   49,   51,
             ...
              980,  981,  997, 1015, 1018, 1031, 1037, 1043, 1050, 1055],
            dtype='int64', length=146),
 'Other (please specify)': Int64Index([   1,    9,  154,  216,  221,  233,  249,  265,  301,  336,  380,
              435,  444,  447,  513,  550,  749,  750,  784,  807,  860,  872,
              905, 1000, 1007],
            dtype='int64')}

In [ ]:
grouped.size()

In [27]:
#grouped.size()
data["What type of cranberry saucedo you typically have?"].value_counts(dropna=False)

Canned                    502
Homemade                  301
None                      146
NaN                        84
Other (please specify)     25
Name: What type of cranberry saucedo you typically have?, dtype: int64

In [39]:
for name, group in grouped:
    print(name)
    print(group.shape)
    print(type(group))

Rural
(216,)
<class 'pandas.core.series.Series'>
Suburban
(496,)
<class 'pandas.core.series.Series'>
Urban
(236,)
<class 'pandas.core.series.Series'>

In [38]:
grouped["income"]

Exception: Column(s) What is typically the main dish at your Thanksgiving dinner? already selected

In [ ]:
grouped["income"].size()

In [ ]:
print(data["income"])

In [37]:
#Aggregating Values
#select avg(income) group by sauce
grouped["income"].agg(np.mean)

Exception: Column(s) What is typically the main dish at your Thanksgiving dinner? already selected

In [ ]:
grouped.agg(np.mean)

In [ ]:
grouped.describe()

In [36]:
#Data Visulalization
%matplotlib inline

sauce = grouped.agg(np.mean)
sauce

DataError: No numeric types to aggregate

In [35]:
#sauce["income"].plot(kind="bar")
sauce["income"]("canned").plot(kind="pie")

NameError: name 'sauce' is not defined

In [ ]:
sauce["income"].plot(kind="bar")

In [ ]:
#select avg(all columns) group by sauce,dish
grouped = data.groupby(["What type of cranberry saucedo you typically have?", "What is typically the main dish at your Thanksgiving dinner?"])
grouped.agg(np.mean)

In [30]:
grouped["income"].agg([np.mean, np.sum, np.std]).head(10)

,mean,sum,std
What type of cranberry saucedo you typically have?,,,
Canned,83823.403409,36882297.5,55835.478014
Homemade,94878.107287,23434892.5,62251.937645
None,78886.084034,9387444.0,54562.750866
Other (please specify),86629.978261,1992489.5,54175.781001

In [31]:
#Apply Method
#selet count(*) group by on living,dish
grouped = data.groupby("How would you describe where you live?")["What is typically the main dish at your Thanksgiving dinner?"]
#grouped["income"].value_counts()
grouped.apply(lambda x:x.value_counts())

How would you describe where you live?
Rural                                   Turkey                    189
                                        Other (please specify)      9
                                        Ham/Pork                    7
                                        Tofurkey                    3
                                        I don't know                3
                                        Turducken                   2
                                        Chicken                     2
                                        Roast beef                  1
Suburban                                Turkey                    449
                                        Ham/Pork                   17
                                        Other (please specify)     13
                                        Tofurkey                    9
                                        Chicken                     3
                                        Roast beef                  3
                                        Turducken                   1
                                        I don't know                1
Urban                                   Turkey                    198
                                        Other (please specify)     13
                                        Tofurkey                    8
                                        Chicken                     7
                                        Roast beef                  6
                                        Ham/Pork                    4
Name: What is typically the main dish at your Thanksgiving dinner?, dtype: int64

In [32]:
grouped.describe()

                                       count unique     top freq
How would you describe where you live?
Rural                                    216      8  Turkey  189
Suburban                                 496      8  Turkey  449
Urban                                    236      6  Turkey  198

In [33]:
import pandas as pd

df = pd.DataFrame({"Name":["Alice", "Bob", "Mallory", "Mallory", "Bob" , "Mallory"],
                    "City":["Seattle","Seattle","Portland","Seattle","Seattle","Portland"]})
print (df)

       City     Name
0   Seattle    Alice
1   Seattle      Bob
2  Portland  Mallory
3   Seattle  Mallory
4   Seattle      Bob
5  Portland  Mallory

In [34]:
#to store in another dataframe
df = df['TIME'].groupby(df['Name']).min()
df = df.to_frame()
df = df.reset_index(level=['Name',"TIME"])

#another way to make a new dataframe after goupby
almo_grp_data = pd.DataFrame({'Qty_cnt' :
almo_slt_models_data.groupby( ['orderDate','Item','State Abv']
          )['Qty'].sum()}).reset_index()

KeyError: 'TIME'

In [ ]:
df.to_csv('file1.csv')